/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.*;
import control.*;
import da.*;
import domain.*;
/**
 *
 * @author User
 */
public class HelpMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public HelpMenu() {
        initComponents();
        setSize(1260,760);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Welcome to Help Center");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 30, 620, 90);

        jButton12.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages22.fw.png"))); // NOI18N
        jButton12.setText("- Add Bus");
        jButton12.setBorder(null);
        jButton12.setOpaque(false);
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages21.fw.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(670, 180, 170, 30);

        jButton13.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages23.fw.png"))); // NOI18N
        jButton13.setText("- Search Bus");
        jButton13.setBorder(null);
        jButton13.setOpaque(false);
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages24.fw.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(670, 210, 170, 30);

        jButton14.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages26.fw.png"))); // NOI18N
        jButton14.setText("- Update Bus");
        jButton14.setBorder(null);
        jButton14.setOpaque(false);
        jButton14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages25.fw.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(670, 240, 170, 30);

        jButton15.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages27.fw.png"))); // NOI18N
        jButton15.setText("- Delete Bus");
        jButton15.setBorder(null);
        jButton15.setOpaque(false);
        jButton15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages28.fw.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(670, 270, 170, 30);

        jLabel4.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stafflabel.png"))); // NOI18N
        jLabel4.setText("Staff Module");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 130, 190, 70);

        jButton6.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages.fw.png"))); // NOI18N
        jButton6.setText("- Add Staff");
        jButton6.setBorder(null);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages9.fw.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(50, 190, 180, 30);

        jButton7.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages1.fw.png"))); // NOI18N
        jButton7.setText("- Retrieve Staff");
        jButton7.setBorder(null);
        jButton7.setOpaque(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages8.fw.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(50, 220, 180, 30);

        jButton8.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages2.fw.png"))); // NOI18N
        jButton8.setText("- Update Staff");
        jButton8.setBorder(null);
        jButton8.setOpaque(false);
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages7.fw.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(50, 250, 180, 30);

        jButton9.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages3.fw.png"))); // NOI18N
        jButton9.setText("- Delete Staff");
        jButton9.setBorder(null);
        jButton9.setOpaque(false);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages5.fw.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(50, 280, 180, 30);

        jButton10.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages4.fw.png"))); // NOI18N
        jButton10.setText("- Search Staff");
        jButton10.setBorder(null);
        jButton10.setOpaque(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages6.fw.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(50, 310, 180, 30);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backicon.fw.png"))); // NOI18N
        jButton11.setContentAreaFilled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backicon2.fw.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(40, 20, 120, 100);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages11.fw.png"))); // NOI18N
        jButton2.setText("- Add Member");
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages10.fw.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 190, 210, 30);

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages14.fw.png"))); // NOI18N
        jButton3.setText("- Retrieve Member");
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages13.fw.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(340, 220, 210, 30);

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages15.fw.png"))); // NOI18N
        jButton4.setText("- Update Member");
        jButton4.setBorder(null);
        jButton4.setOpaque(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages16.fw.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(340, 250, 210, 30);

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages18.fw.png"))); // NOI18N
        jButton5.setText("- Delete Member");
        jButton5.setBorder(null);
        jButton5.setOpaque(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages17.fw.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(340, 280, 210, 30);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages19.fw.png"))); // NOI18N
        jButton1.setText("- Search Member");
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages20.fw.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 310, 210, 30);

        jLabel5.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/memberlabel.png"))); // NOI18N
        jLabel5.setText("Member Module");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 130, 220, 70);

        jLabel6.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buslabel.fw.png"))); // NOI18N
        jLabel6.setText("Bus Module");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(670, 130, 190, 70);

        jLabel7.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 153));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/schedulelabel.fw.png"))); // NOI18N
        jLabel7.setText("Schedule Module");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(950, 130, 230, 70);

        jButton22.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages29.fw.png"))); // NOI18N
        jButton22.setText("- Add Staff");
        jButton22.setBorder(null);
        jButton22.setOpaque(false);
        jButton22.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages30.fw.png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22);
        jButton22.setBounds(950, 190, 230, 30);

        jButton23.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages32.fw.png"))); // NOI18N
        jButton23.setText("- Search Schedule");
        jButton23.setBorder(null);
        jButton23.setOpaque(false);
        jButton23.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages31.fw.png"))); // NOI18N
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23);
        jButton23.setBounds(950, 220, 230, 30);

        jButton24.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages33.fw.png"))); // NOI18N
        jButton24.setText("- Update Schedule");
        jButton24.setBorder(null);
        jButton24.setOpaque(false);
        jButton24.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages34.fw.png"))); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24);
        jButton24.setBounds(950, 250, 230, 30);

        jButton25.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages36.fw.png"))); // NOI18N
        jButton25.setText("- Delete Schedule");
        jButton25.setBorder(null);
        jButton25.setOpaque(false);
        jButton25.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages35.fw.png"))); // NOI18N
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25);
        jButton25.setBounds(950, 280, 230, 30);

        jLabel8.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 153));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ticketlabel.fw.png"))); // NOI18N
        jLabel8.setText("Purchase Module");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 380, 250, 70);

        jButton27.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages37.fw.png"))); // NOI18N
        jButton27.setText("- Add Purchase");
        jButton27.setBorder(null);
        jButton27.setOpaque(false);
        jButton27.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages38.fw.png"))); // NOI18N
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27);
        jButton27.setBounds(50, 440, 240, 30);

        jButton28.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages66.fw.png"))); // NOI18N
        jButton28.setBorder(null);
        jButton28.setLabel("- Search Purchase");
        jButton28.setOpaque(false);
        jButton28.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages65.fw.png"))); // NOI18N
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28);
        jButton28.setBounds(50, 470, 240, 30);

        jButton29.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages41.fw.png"))); // NOI18N
        jButton29.setText("- Change Purchase");
        jButton29.setBorder(null);
        jButton29.setOpaque(false);
        jButton29.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages42.fw.png"))); // NOI18N
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29);
        jButton29.setBounds(50, 500, 240, 30);

        jButton30.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages43.fw.png"))); // NOI18N
        jButton30.setText("- Cancel Purchase");
        jButton30.setBorder(null);
        jButton30.setOpaque(false);
        jButton30.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages44.fw.png"))); // NOI18N
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30);
        jButton30.setBounds(50, 530, 240, 30);

        jLabel9.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 153));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insurancelabel.fw.png"))); // NOI18N
        jLabel9.setText("Insurance Module");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 390, 250, 70);

        jButton32.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages46.fw.png"))); // NOI18N
        jButton32.setText("- Add Insurance");
        jButton32.setBorder(null);
        jButton32.setOpaque(false);
        jButton32.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages45.fw.png"))); // NOI18N
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32);
        jButton32.setBounds(340, 450, 250, 30);

        jButton33.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages47.fw.png"))); // NOI18N
        jButton33.setText("- Retrieve Insurance");
        jButton33.setBorder(null);
        jButton33.setOpaque(false);
        jButton33.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages48.fw.png"))); // NOI18N
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33);
        jButton33.setBounds(340, 480, 250, 30);

        jButton34.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages50.fw.png"))); // NOI18N
        jButton34.setText("- Update Insurance");
        jButton34.setBorder(null);
        jButton34.setOpaque(false);
        jButton34.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages49.fw.png"))); // NOI18N
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34);
        jButton34.setBounds(340, 510, 250, 30);

        jButton35.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages51.fw.png"))); // NOI18N
        jButton35.setText("- Delete Insurance");
        jButton35.setBorder(null);
        jButton35.setOpaque(false);
        jButton35.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages52.fw.png"))); // NOI18N
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton35);
        jButton35.setBounds(340, 540, 250, 30);

        jButton36.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages54.fw.png"))); // NOI18N
        jButton36.setText("- Search Insurance");
        jButton36.setBorder(null);
        jButton36.setOpaque(false);
        jButton36.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages53.fw.png"))); // NOI18N
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton36);
        jButton36.setBounds(340, 570, 250, 30);

        jLabel10.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 153));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paymentlabel.fw.png"))); // NOI18N
        jLabel10.setText("Payment Module");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(660, 430, 220, 70);

        jButton18.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages55.fw.png"))); // NOI18N
        jButton18.setText("- Add Staff");
        jButton18.setBorder(null);
        jButton18.setOpaque(false);
        jButton18.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages56.fw.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(670, 490, 210, 30);

        jButton37.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages58.fw.png"))); // NOI18N
        jButton37.setText("- Retrieve Payment");
        jButton37.setBorder(null);
        jButton37.setOpaque(false);
        jButton37.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StaffBGimages57.fw.png"))); // NOI18N
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton37);
        jButton37.setBounds(670, 520, 210, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/helpbg.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(1150, 760));
        jLabel1.setRequestFocusEnabled(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1260, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
         JOptionPane.showMessageDialog(null,"Guide you how to properly delete Bus!\n\nStep 1: Select the bus you want to delete.\nStep 2: Click the yes button to delete the bus information.\n\nAt last will show the successfully message if the bus had been deleted.", "Help (Add Bus)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"Guide you how to properly add Bus!\n\nStep 1: Click the add button.\nStep 2: Key in the plate number of bus.\nStep 3: Select the Driver ID of the bus.\nStep 4: Click confirm to add the new bus.\n\nAt last will show the successfully message if the new bus is added.", "Help (Delete Bus)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
         JOptionPane.showMessageDialog(null,"Guide you how to properly search bus information!\n\nStep 1: Key in the bus no u want to search.\nStep 2: Click the read bus no to search the bus information.\n\n\nAt last you can search the bus information.", "Help (Search Bus)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Guide you how to properly update Bus information!\n\nStep 1: Select the bus you want to update.\nStep 2: Select the Driver ID and key in the Plate number of the bus.\nStep 3: Selete the Driver ID of the bus.\nStep 4: Click confirm to update the bus information.\n\nAt last will show the successfully message if the bus had been updated.", "Help (Update Bus)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here
        JOptionPane.showMessageDialog(null,"Guide you how to properly Add !\n\nStep 1: Click the <Add> button.\nStep 2: The Message Dialog will show the new staff ID for the new staff.\nStep 3: Key in staff name.\nStep 4: Key in staff position by chosing the option number 1 to 4.\nStep 5: Key in staff password.\nStep 6:Choose the gender option number.\nStep 7: Key in staff contact number.\n\nAt last, It will show a successfully added message.", "Help (Add Staff)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Guide you how to properly retrieve !\n\nStep 1: Key in the staff ID you want to retrieve.\nStep 2: And click <check> button to retrieve staff.\nStep 3: It will show the relevant staff details at the following textfield.\n\nAt last, you can retrieve the relevant staff details.", "Help (Retrieve Staff)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Guide you how to properly update !\n\nStep 1: Key in the staff ID you want to update.\nStep 2: And click <check> to check the record first.\nStep 3: Click <Edit> button to update.\nStep 4: It will show a message to ask you whether update name or not, <Yes, edit> or <No, Remains>\n             Option 1: Click <Yes, edit>, then need to key in the name you want to update.\n             Option 2: Click <No, Remains>, then go to next step.\nStep 5: The staff position, password, gender, contact number same like <Stap 4> just update the new or remains.\n\nAt last, show a message that you are successfully updated.", "Help (Update Staff)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Guide you how to properly delete !\n\nStep 1: Key in the staff ID you want to delete.\nStep 2: And click <check> button to check the record first.\nStep 3: Click <Delete> to delete the Staff ID record you check.\nStep 4: It will show a confirmation message <Yes> to delete the record or <No> to cancel delete.\n\nAt last, will show a message successfully deleted if you are clicking <Yes>", "Help (Delete Staff)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly search staff !\n\nStep 1: Key in the staff ID in the field.\nStep 2: Click <Search> button to search information\n\nAt last, the staff details you search will show out.", "Help (Search Staff)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jButton11.setContentAreaFilled(false);
        jButton11.setBorder(null);
        jButton11.setOpaque(false);
        dispose();
        new HelpMenu();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly Add !\n\nStep 1: Click the <Add> button.\nStep 2: The Message Dialog will show the new member ID for the new member.\nStep 3: Key in member name.\nStep 4: Key in member IC with 12 digits.\nStep 5: Key in member gender by choosing the option number.\nStep 6: Key in member contact number.\n\nAt last, It will show a successfully added message.", "Help (Add Member)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly retrieve !\n\nStep 1: Key in the member ID you want to retrieve.\nStep 2: And click <check> button to retrieve member.\nStep 3: It will show the relevant member details at the following textfield.\n\nAt last, you can retrieve the relevant member details.", "Help (Retrieve Member)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly update !\n\nStep 1: Key in the member ID you want to update.\nStep 2: And click <check> to check the record first.\nStep 3: Click <Edit> button to update.\nStep 4: It will show a message to ask you whether update name or not, <Yes, edit> or <No, Remains>\n             Option 1: Click <Yes, edit>, then need to key in the name you want to update.\n             Option 2: Click <No, Remains>, then go to next step.\nStep 5: The member IC, gender, contact number same like <Stap 4> just update the new or remains.\n\nAt last, show a message that you are successfully updated.", "Help (Update Member)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly delete !\n\nStep 1: Key in the member ID you want to delete.\nStep 2: And click <check> button to check the record first.\nStep 3: Click <Delete> to delete the Member ID record you check.\nStep 4: It will show a confirmation message <Yes> to delete the record or <No> to cancel delete.\n\nAt last, will show a message successfully deleted if you are clicking <Yes>", "Help (Delete Member)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JOptionPane.showMessageDialog(null,"Guide you how to properly search member !\n\nStep 1: Key in the member ID in the field.\nStep 2: Click <Search> button to search information\n\nAt last, the member details you search will show out.", "Help (Search Member)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly add Schedule!\n\nStep 1: Click the date button to select the date.\nStep 2: Select the time of schedule from combo box.\nStep 3: Select the starting point of schedule from combo box.\nStep 4: Select the destination of schedule from combo box.\nStep 5: Select the Bus no of schedule from combo box.\nStep 6: Click the add button to add the new schedule.\n\nAt last will show the successfully message if the new Schedule had been Added!", "Help (Add Schedule)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
         JOptionPane.showMessageDialog(null,"Guide you how to properly search schedule information!\n\nStep 1: Key in the schedule no u want to search.\nStep 2: Click the read schedule no to search the schedule information.\n\nAt last you can search the schedule information.", "Help (Search Schedule)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly update Schedule information!\n\nStep 1: Select the Schedule no you want to update from combo box.\nStep 2: Click the retrieve button the retrieve the schedule information.\nStep 3: You can change the date, time, busno, starting point, destination of the schedule.\nStep 4: Click confirm to update the schedule.information.\n\nAt last will show the successfully message if the schedule had been updated.", "Help (Update Schedule)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly delete schedule!\n\nStep 1: Select the schedule you want to delete.\nStep 2: Click the retrieve button the retrieve the schedule information.\nStep 3: Click confirm to delete the schedule information.\n\nAt last will show the successfully message if the schedule had been deleted.", "Help (Delete Schedule)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
       JOptionPane.showMessageDialog(null,"Guide you how to properly add Purchase!\n\nStep 1: Select the Member ID of purchase from combo box.\nStep 2: Select the Receptionist ID of purchase from combo box.\nStep 3: Select the Schedle ID of purchase from combo box.\nStep 4: Select the Insurance ID of purchase from combo box.\nStep 5: Click the check button to check the status of the seat.\nStep 6: Select the Seat no of purchase from combo box.\nStep 7: Click the Make Purchase button to add the new purchase!\n\nAt last will show the successfully message if the new purchase had been added!", "Help (Add Purchase)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly search Purchase information!\n\nStep 1: Key in the Purchase ID u want to search\nStep 2: Click the read Purchase ID to search the Purchase information.\n\nAt last you can search the Purchase information.", "Help (Search Purchase)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly update Purchase information!\n\nStep 1: Select the Purchase no you want to update from combo box.\nStep 2: Click the retrieve button the retrieve the Purchase information.\nStep 3: You can change the Memberid, Receptionist ID, Schedule ID, Insurance ID, and the seat of the schedule.\nStep 4: Click confirm to update the Purchase.\n\nAt last will show the successfully message if the Purchase had been updated.", "Help (Change Purchase)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly delete Purchase!\n\nStep 1: Select the Purchase you want to delete.\nStep 2: Click the retrieve button the retrieve the Purchase information.\nStep 3: Click confirm to delete the Purchase information.\n\nAt last will show the successfully message if the Purchase had been deleted.", "Help (Cancel Purchase)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
         JOptionPane.showMessageDialog(null,"Guide you how to properly Add !\n\nStep 1: Click the <Add> button.\nStep 2: The Message Dialog will show the new insurance ID for the new insurance package.\nStep 3: Key in insurance price.\nStep 4: Key in insurance description.\n\nAt last, It will show a successfully added message.", "Help (Add Insurance)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly retrieve !\n\nStep 1: Key in the insurance ID you want to retrieve.\nStep 2: And click <check> button to retrieve insurance.\nStep 3: It will show the relevant insurance details at the following textfield.\n\nAt last, you can retrieve the relevant insurance details.", "Help (Retrieve Insurance)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly update !\n\nStep 1: Key in the insurance ID you want to update.\nStep 2: And click <check> to check the record first.\nStep 3: Click <Edit> button to update.\nStep 4: It will show a message to ask you whether update insurance price or not, <Yes, edit> or <No, Remains>\n             Option 1: Click <Yes, edit>, then need to key in the insurance price you want to update.\n             Option 2: Click <No, Remains>, then go to next step.\nStep 5: The insurance description same like <Stap 4> just update the new or remains.\n\nAt last, show a message that you are successfully updated.", "Help (Update Insurance)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly delete !\n\nStep 1: Key in the insurance ID you want to delete.\nStep 2: And click <check> button to check the record first.\nStep 3: Click <Delete> to delete the Insurance ID record you check.\nStep 4: It will show a confirmation message <Yes> to delete the record or <No> to cancel delete.\n\nAt last, will show a message successfully deleted if you are clicking <Yes>", "Help (Delete Member)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly search insurance !\n\nStep 1: Key in the insurance ID in the field.\nStep 2: Click <Search> button to search information\n\nAt last, the insurance details you search will show out.", "Help (Search Insurance)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        JOptionPane.showMessageDialog(null,"Guide you how to properly add Payment!\n\nStep 1: Select the Purchase ID of Payment from combo box.\nStep 2: Select the Receptionist ID of Payment from combo box.\nStep 3: Select the payment method is pay by cash or credit card.\nStep 4: If pay by cash, the key in the total amount the customer pay and press enter.\nStep 5: If pay by credit card, the system will automatically calculate the balance of the payment.\nStep 6: Click the payment button to add the new payment!\n\nAt last will show the successfully message if the new payment had been added!", "Help (Add Payment)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
       JOptionPane.showMessageDialog(null,"Guide you how to properly search payment information!\n\nStep 1: Key in the payment ID u want to search.\nStep 2: Click the read payment ID to search the payment information.\n\nAt last you can search the payment information.", "Help (Search Payment)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton37ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
